"""increase_status_len

Revision ID: c79a5ec758bc
Revises: 20260604_0010
Create Date: 2026-06-04 06:18:56.838656+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c79a5ec758bc'
down_revision: Union[str, None] = '20260604_0010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wb_financial_daily_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('gross_revenue', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('for_pay', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('wb_costs', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cogs', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('profit_before_tax', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('profit_after_tax', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('raw_row_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seller_id', 'summary_date', name='uq_wb_financial_daily_summary')
    )
    op.create_index(op.f('ix_wb_financial_daily_summary_seller_id'), 'wb_financial_daily_summary', ['seller_id'], unique=False)
    op.create_index(op.f('ix_wb_financial_daily_summary_summary_date'), 'wb_financial_daily_summary', ['summary_date'], unique=False)
    op.create_table('wb_financial_monthly_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('summary_month', sa.Date(), nullable=False),
    sa.Column('gross_revenue', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('for_pay', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('wb_costs', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cogs', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('profit_before_tax', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('profit_after_tax', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('raw_row_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seller_id', 'summary_month', name='uq_wb_financial_monthly_summary')
    )
    op.create_index(op.f('ix_wb_financial_monthly_summary_seller_id'), 'wb_financial_monthly_summary', ['seller_id'], unique=False)
    op.create_index(op.f('ix_wb_financial_monthly_summary_summary_month'), 'wb_financial_monthly_summary', ['summary_month'], unique=False)
    op.create_index(op.f('ix_payment_transactions_created_at'), 'payment_transactions', ['created_at'], unique=False)
    op.drop_constraint('seller_finance_automation_state_seller_id_key', 'seller_finance_automation_state', type_='unique')
    op.drop_index('ix_seller_finance_automation_state_seller_id', table_name='seller_finance_automation_state')
    op.create_index(op.f('ix_seller_finance_automation_state_seller_id'), 'seller_finance_automation_state', ['seller_id'], unique=True)
    op.drop_constraint('sellers_store_id_key', 'sellers', type_='unique')
    op.drop_index('ix_sellers_store_id', table_name='sellers')
    op.create_index(op.f('ix_sellers_store_id'), 'sellers', ['store_id'], unique=True)
    op.alter_column('generated_image_jobs', 'status', existing_type=sa.String(length=20), type_=sa.String(length=40))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generated_image_jobs', 'status', existing_type=sa.String(length=40), type_=sa.String(length=20))
    op.drop_index(op.f('ix_sellers_store_id'), table_name='sellers')
    op.create_index('ix_sellers_store_id', 'sellers', ['store_id'], unique=False)
    op.create_unique_constraint('sellers_store_id_key', 'sellers', ['store_id'])
    op.drop_index(op.f('ix_seller_finance_automation_state_seller_id'), table_name='seller_finance_automation_state')
    op.create_index('ix_seller_finance_automation_state_seller_id', 'seller_finance_automation_state', ['seller_id'], unique=False)
    op.create_unique_constraint('seller_finance_automation_state_seller_id_key', 'seller_finance_automation_state', ['seller_id'])
    op.drop_index(op.f('ix_payment_transactions_created_at'), table_name='payment_transactions')
    op.drop_index(op.f('ix_wb_financial_monthly_summary_summary_month'), table_name='wb_financial_monthly_summary')
    op.drop_index(op.f('ix_wb_financial_monthly_summary_seller_id'), table_name='wb_financial_monthly_summary')
    op.drop_table('wb_financial_monthly_summary')
    op.drop_index(op.f('ix_wb_financial_daily_summary_summary_date'), table_name='wb_financial_daily_summary')
    op.drop_index(op.f('ix_wb_financial_daily_summary_seller_id'), table_name='wb_financial_daily_summary')
    op.drop_table('wb_financial_daily_summary')
    # ### end Alembic commands ###
